# Compose stack for running FastAPI backend and Next.js frontend locally.
# version: "3.9"

services:
  backend:
    # Runs the FastAPI app with hot reload via volume mounts.
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    command: bash -lc "pip install --no-cache-dir -r requirements.txt && uvicorn app.main:app --host 0.0.0.0 --port 8000"

  frontend:
    # Serves the Next.js client against the locally running backend.
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
    environment:
      - NEXT_TELEMETRY_DISABLED=1
    ports:
      - "3000:3000"
    command: bash -lc "npm install && npm run dev"
    depends_on:
      - backend
